  version: '3'
  services:
    psono_db:
      image: postgres:10.4
      container_name: psono_db
      environment:
        - POSTGRES_USER=psono
        - POSTGRES_PASSWORD=psono
        - POSTGRES_DB=psono
        - DB_EXTENSION=pgcrypto
        - DB_EXTENSION=ltree
      volumes:
        - "psonodb:/var/lib/postgresql/data"
      networks:
        - backend
      ports:
        - "5432:5432"
      restart: always

    psono_backend:
      image: psono/psono-server:latest
      container_name: psono_backend
      volumes:
        - "${PWD}/settings.yaml:/root/.psono_server/settings.yaml"
      links:
        - psono_db
      networks:
        - backend
      ports:
        - "10100:80"
      restart: always
      depends_on:
        - psono_db

    psono_reverse:
      image: nginx:latest
      container_name: psono_reverse
      volumes:
        - "${PWD}/vhost.conf:/etc/nginx/conf.d/vhost.conf"
        - "${PWD}/ssl:/etc/ssl"
      networks:
        - backend
        - outside
      ports:
        - "443:443"
      restart: always
      depends_on:
        - psono_db
        - psono_backend

    psono_client:
      image: psono/psono-client:latest
      container_name: psono_client
      networks:
        - backend
      ports:
        - "10101:80"
      restart: always
      depends_on:
        - psono_db
        - psono_backend

    psono_admin:
      image: psono/psono-admin-client:latest
      container_name: psono_admin
      networks:
        - backend
      ports:
        - "10102:80"
      restart: always
      depends_on:
        - psono_db
        - psono_backend
  volumes:
    psonodb:
    #  external: true

  networks:
    outside:
      external: true
    backend:
